#!/bin/bash
set -e

echo "Pre-commit: Running RuboCop..."
bundle exec rubocop

echo "Pre-commit: Generating sample reports..."
bundle exec rake reports:generate_samples
git add data/samples/reports/

if [ "${JIRA_ENV:-}" != "gha" ]; then
  echo "Pre-commit: Syncing CI badges in README..."
  bundle exec badge badges sync --org cbp-org --repo predictability-engine
  git add README.md
fi
