AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context
    - feature
    - scenario
    - Given
    - When
    - Then
    - And

Style/Documentation:
  Enabled: false
